version: '3'

services:
        web:
            build: .
            ports:
                - 8000:8000

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24