# Generated by Django 3.1.7 on 2021-07-22 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='forbidden_map',
            field=models.ImageField(upload_to=website.models.map_dir_path),
        ),
        migrations.AlterField(
            model_name='map',
            name='height_map',
            field=models.ImageField(upload_to=website.models.map_dir_path),
        ),
        migrations.AlterField(
            model_name='map',
            name='visual_map',
            field=models.ImageField(upload_to=website.models.map_dir_path),
        ),
        migrations.CreateModel(
            name='Map_Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_address', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('working_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.map')),
            ],
        ),
    ]
