# Generated by Django 3.1.7 on 2021-08-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='map',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.map'),
            preserve_default=False,
        ),
    ]
