# Generated by Django 3.1.7 on 2021-08-01 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_history_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
