# Generated by Django 3.1.7 on 2021-09-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210919_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='height_meter',
        ),
    ]
